name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      anki_version:
        description: 'Anki Version'
        required: true
        default: '25.02'  # Default to 'latest', you can modify this as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --build-arg ANKI_VERSION=${{ github.event.inputs.anki_version }} -t your-image-name .

      - name: Extract anki-sync-server binary
        run: |
          # Create a temporary directory to store the extracted binary
          mkdir -p extracted
          # Copy the binary from the builder image to the local file system
          docker create --name temp-container your-image-name
          docker cp temp-container:/usr/local/bin/anki-sync-server extracted/anki-sync-server
          docker rm temp-container

      - name: Upload anki-sync-server binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: anki-sync-server-binary
          path: extracted/anki-sync-server

      - name: Clean up
        run: docker system prune -f
